bedside/urls.py
#from djangorestframework.resources import ModelResource
#from djangorestframework.views import ListOrCreateModelView, InstanceModelView
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.views import login
#from views import Givings, Giving

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('bedside.views',
    # Examples:
    # url(r'^$', 'prose_django.views.home', name='home'),
    # url(r'^prose_django/', include('prose_django.foo.urls')),
    #(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^i18n/', include('django.conf.urls.i18n')),
	#url(r'^mobi/', 'mobi'),
	url(r'^$', 'start'),
	url(r'^doc$', 'doc'),
	url(r'^nurse$', 'nurse'),
	url(r'^doc/submit$', 'submit_doc'),
	url(r'^nurse/submit$', 'submit_nurse'),
	
	
	#url(r'^accounts/profile/$', 'givings'),
	#url(r'^givings/$', Givings.as_view(), name='givings'),
	#url(r'^givings/$', 'givings'),
	#url(r'^givings/(?P<gid>\d+)/$', Giving.as_view(), name='giving'),
	#url(r'^givings/compile/(?P<gid>\d+)/$', 'givings_compile_ui'),
	#url(r'^givings/getxml/(?P<gid>\d+)/$', 'givings_get_xml'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'prose_django.views.home', name='home'),
    # url(r'^prose_django/', include('prose_django.foo.urls')),
	(r'^', include('bedside.urls')),
	
	#url(r'^givings/compile/(?P<quid>\d+)/$', 'givings_compile'),
	
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
)

bedside/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

"""class User(models.Model):
	uid = models.AutoField(primary_key=True)
	email = models.CharField(max_length=200, unique=True)
	password = models.CharField(max_length=16)
	class Meta:
		db_table = 'User'
	def __unicode__(self):
		return self.email
"""

class Patient(models.Model):
	pid = models.ForeignKey(User, primary_key=True)
	#name = models.CharField(max_length=200)
	class Meta:
		db_table = 'Patient'
	def __unicode__(self):
		return str(self.pid)

class Doctor(models.Model):
	did = models.ForeignKey(User, primary_key=True)
	pid = models.ManyToManyField(Patient)
	#name = models.CharField(max_length=200)
	class Meta:
		db_table = 'Doctor'
	def __unicode__(self):
		return str(self.did.first_name)

class Questionnaire(models.Model):
	quid = models.AutoField(primary_key=True)
	created_by = models.ForeignKey(Doctor)
	description = models.CharField(max_length=1000, null=True)
	class Meta:
		db_table = 'Questionnaire'
	def __unicode__(self):
		return str(self.quid)
	def natural_key(self):
		return (self.quid)

class Questionnaire_Lang(models.Model):
	quid = models.ForeignKey(Questionnaire)
	lang = models.CharField(max_length=5)
	title = models.CharField(max_length=1000)
	info = models.TextField()
	class Meta:
		unique_together = ('quid', 'lang')
	def __unicode__(self):
		return str(self.quid)

class Question(models.Model):
	qid = models.AutoField(primary_key=True)
	quid = models.ForeignKey(Questionnaire)
	type = models.CharField(max_length=3)
	left_val = models.DecimalField(max_digits=32, decimal_places=16)
	right_val = models.DecimalField(max_digits=32, decimal_places=16)
	description = models.CharField(max_length=500, null=True)
	class Meta:
		db_table = 'Question'
	def __unicode__(self):
		return str(self.quid) + ':' + str(self.qid) + ' ' + self.description

class Question_Lang(models.Model):
	qid = models.ForeignKey(Question)
	lang = models.CharField(max_length=5)
	string = models.CharField(max_length=500)
	class Meta:
		unique_together = ('qid', 'lang')
	def __unicode__(self):
		return str(self.qid.quid) + ':' + str(self.qid.qid) + ' (' + self.lang + '): ' + self.string

class Option(models.Model):
	oid = models.AutoField(primary_key=True)
	qid = models.ForeignKey(Question)
	lang = models.CharField(max_length=5)
	description = models.CharField(max_length=500)
	class Meta:
		db_table = 'Option'
	def __unicode__(self):
		return self.description

class Giving(models.Model):
	gid        = models.AutoField(primary_key=True)
	did        = models.ForeignKey(Doctor)
	pid        = models.ForeignKey(Patient)
	quid       = models.ForeignKey(Questionnaire)
	from_date  = models.DateTimeField()
	to_date    = models.DateTimeField()
	given_date = models.DateTimeField(auto_now=True)
	completed  = models.BooleanField(default=False)
	class Meta:
		db_table = 'Giving'
	def __unicode__(self):
		return str(self.gid) + ' given to patient ' + str(self.pid) + ' from doc ' + str(self.did)

class Outcome(models.Model):
	outid  = models.AutoField(primary_key=True)
	gid    = models.ForeignKey(Giving)
	qid    = models.ForeignKey(Question)
	oid    = models.ForeignKey(Option, null=True)
	num    = models.DecimalField(max_digits=32, decimal_places=16, null=True)
	string = models.CharField(max_length=5, null=True)
	date   = models.DateTimeField(auto_now=True)
	class Meta:
		db_table = 'Outcome'
	

bedside/views.py
from django.http import *
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _
from django.core import serializers
from django.core.urlresolvers import reverse
from django.template import Template, Context, RequestContext
from django.shortcuts import render_to_response
from models import *
import simplejson


def start(request):
	return render_to_response('app.html', {}, RequestContext(request))
	
#@login_required
def nurse(request):
	return render_to_response('app-nurse.html', {'user_role_str':'Infermiere', 'user_name':'Anna Bianchi'}, RequestContext(request))

#@login_required
def doc(request):
	return render_to_response('app-doc.html', {'user_role_str':'Medico', 'user_name':'Mario Brossi'}, RequestContext(request))

#@login_required
def submit_nurse(request):
	return render_to_response('app-submit-ok.html', {'user_role':'nurse'}, RequestContext(request))

#@login_required
def submit_doc(request):
	return render_to_response('app-submit-ok.html', {'user_role':'doc'}, RequestContext(request))





@login_required
def givings(request):
	if not 'django_language' in request.session:
		request.session['django_language'] = 'it' # <-- Setta lingua del browser invece
	if request.method == 'POST': return HttpResponseNotAllowed(['GET'])
	# If patient
	todo = Giving.objects.filter(pid=request.user.pk).select_related()
	return render_to_response('quest_list.html', {'todo':todo}, RequestContext(request))

@login_required
def givings_compile_ui(request, gid):
	#@todo Bisogna controllare che l'utente ha i diritti di accesso al questionario
	return render_to_response('compile.html', {'gid':gid}, context_instance=RequestContext(request))

@login_required
def givings_get_xml(request, gid):
	try:
		giving = Giving.objects.get(pk=gid)
	except:
		return HttpResponseNotFound()
	#@todo Bisogna controllare che l'utente ha i diritti di accesso al questionario
	questionnaire = Question.objects.filter(quid=giving.quid).select_related()
	return render_to_response('questionnaire.xml', {'q':questionnaire}, RequestContext(request), mimetype='application/xml')

#def mobi(request):
	# Se sei loggato vai a /givings senno' a /login
#	if request.method == 'POST': return HttpResponseNotAllowed(['GET'])
#	return login(request)


""" Chiamata via Ajax
def login(request):
	if request.method == 'POST':
		# Per ora faccio un login sempre valido
		json = simplejson.dumps({'login_success': True})
		response = HttpResponse(json, mimetype='application/json')
		response.set_cookie('email', value=request.POST.get('email'))
		response.set_cookie('lang', value='it')
		request.session['django_language'] = 'it' ## <-- Metti lingua del browser
		return response
	else:
		return render_to_response('login.html', RequestContext(request))
"""

templates/app-doc.html
{% extends "mobi.html" %}

{% block content %}



{% include "jquery-pages/patient-select.html" with page_id="patient-select" %}

{% include "jquery-pages/patient-review.html" with page_id="patient-review" prev_href="#patient-select" prev_str="Back" next_href="#doc1" next_str="Start" %}

{% include "jquery-pages/doc1.html"           with page_id="doc1"           prev_href="#patient-review" prev_str="Back" next_href="#doc2" next_str="Esoscopia" %}

{% include "jquery-pages/doc2.html"           with page_id="doc2"           prev_href="#doc1"           prev_str="Back" next_href="#doc3" next_str="Esito" %}

{% include "jquery-pages/doc3.html"           with page_id="doc3"           prev_href="#doc2"           prev_str="Back" next_href="#doc4" next_str="Conclusioni" %}

{% include "jquery-pages/doc4.html"           with page_id="doc4"           prev_href="#doc3"           prev_str="Back" next_href="doc/submit"     next_str="Submit" %}



{% endblock %}

templates/app-nurse.html
{% extends "mobi.html" %}

{% block content %}



{% include "jquery-pages/patient-select.html" with page_id="patient-select" %}

{% include "jquery-pages/patient-review.html" with page_id="patient-review" prev_href="#patient-select" prev_str="Back" next_href="#nurse1"      next_str="Start" %}

{% include "jquery-pages/nurse1.html"         with page_id="nurse1"         prev_href="#patient-review" prev_str="Back" next_href="#nurse2"      next_str="Next" %}

{% include "jquery-pages/nurse2.html"         with page_id="nurse2"         prev_href="#nurse1"         prev_str="Back" next_href="nurse/submit" next_str="Submit" %}



{% endblock %}

templates/app-submit-ok.html
{% extends "mobi.html" %}

{% block content %}

{% include "jquery-pages/submit-ok.html" with page_id="submit-ok" %}

{% endblock %}

templates/app.html
{% extends "mobi.html" %}

{% block content %}
    
<div data-role="page" id="role-selection" data-theme="d">
	<div data-role="header" data-theme="b">
		<h1>Bedside</h1>
	</div>
	
	<div data-role="content">
		<div>
			<a data-theme="b" data-role="button" href="#doc" class="bigbutton">Medico</a>
		</div>
		<div>
			<a data-theme="c" data-role="button" href="#nurse" class="bigbutton">Infermiere</a>
		</div>
	</div>
</div>

{% include "jquery-pages/login.html" with page_id="doc"   action="doc"   user_role="Medico" %}
{% include "jquery-pages/login.html" with page_id="nurse" action="nurse" user_role="Infermiere" %}

<!--div data-role="page" id="doctor" data-theme="d">
	<div data-role="header" data-theme="b">
		<h1>Bedside</h1>
		<a data-direction="reverse" data-icon="back" href="#role">Back</a>
	</div>
	
	<div data-role="content">
		{% if form.errors %}
			<p>Your username and password didn't match. Please try again.</p>
		{% endif %}
			
		<h3>Login Medico</h3>
		<form action="doc" method="post" id="login-form" data-ajax="false">
			{% csrf_token %}
			<ul data-role="listview" data-inset="true" data-theme="c">
				<li data-role="fieldcontain">
				<div data-role="fieldcontain">
					<label for="username" class="ui-hidden-accessible">Nome utente:</label>
					<input type="text" name="username" id="username" value="" placeholder="Nome utente..."/>
				</div>
				<div data-role="fieldcontain">
					<label for="password" class="ui-hidden-accessible">Password:</label>
					<input type="password" name="password" id="password" value="" placeholder="Password..."/>
				</div>
				</li>
				<li data-role="fieldcontain">
					<button type="submit" data-theme="b">Login</button>
				</li>
			</ul>
		</form>
	</div>
	
</div>

<div data-role="page" id="nurse" data-theme="d">
	<div data-role="header" data-theme="b">
		<h1>Bedside</h1>
		<a data-direction="reverse" data-icon="back" href="#role">Back</a>
	</div>
	
	<div data-role="content">
		{% if form.errors %}
			<p>Your username and password didn't match. Please try again.</p>
		{% endif %}
			
		<h3>Login Infermiere</h3>
		<form action="nurse" method="post" id="login-form" data-ajax="false">
			{% csrf_token %}
			<ul data-role="listview" data-inset="true" data-theme="c">
				<li data-role="fieldcontain">
				<div data-role="fieldcontain">
					<label for="username" class="ui-hidden-accessible">Nome utente:</label>
					<input type="text" name="username" id="username" value="" placeholder="Nome utente..."/>
				</div>
				<div data-role="fieldcontain">
					<label for="password" class="ui-hidden-accessible">Password:</label>
					<input type="password" name="password" id="password" value="" placeholder="Password..."/>
				</div>
				</li>
				<li data-role="fieldcontain">
					<button type="submit" data-theme="b">Login</button>
				</li>
			</ul>
		</form>
	</div>
	
</div-->

{% endblock %}

templates/browser_(unused).html
<!DOCTYPE html>
<html>
    <head>
    <title>Page Title</title>
    <meta charset="utf-8"> 
    <link type="text/css" rel="stylesheet" href="/stylesheets/main.css" />
    
</head>
<body>
    
    <div data-role="page" id="app">
        <div data-role="header">
            <h1>Guestbook</h1>
        </div>
        
        <div data-role="content">
            {% for greeting in greetings %}
                {% if greeting.author %}
                    <b>{{ greeting.author.nickname }}</b> wrote:
                {% else %}
                    An anonymous person wrote:
                {% endif %}
                <blockquote>{{ greeting.content|escape }}</blockquote>
            {% endfor %}
            
            <div data-role="fieldcontain">
            <form action="/sign?{{ guestbook_name_action }}" method="post">
                <div><textarea name="content" rows="3" cols="60"></textarea></div>
                <div><input type="submit" value="Sign Guestbook"></div>
            </form>
            </div>

            <form>Guestbook name: <input value="{{ guestbook_name }}" name="guestbook_name">
                <input type="submit" value="switch"></form>

            <a href="{{ url }}">{{ url_linktext }}</a>
        </div>
        
        <div data-role="footer">
            <h4>P-rose</h4>
        </div>
    </div>
    
    

</body>
</html>

templates/jquery-pages/base-page.html
<div data-role="page" id="{{ page_id }}" data-theme="d">
	
	{% block header %}
	<div data-role="header" data-position="inline" data-theme="b">
		<h1>Bedside</h1>
		<a data-direction="reverse" data-icon="home" data-ajax="false" href="/">Logout</a>		
	</div>
	{% endblock %}
	
	{% block content %}{% endblock %}
	
	{% block footer %}
	<div data-role="footer" {#data-id="footer"#} data-theme="b" {#data-position="fixed"#}>
		<h3>{% now "l j F Y, H:i:s" %}{# Ho provato con DATETIME_FORMAT in settings.py ma non funzia #}</h3>
	</div>
	{% endblock %}
	
</div>

templates/jquery-pages/div-info.html
<div class="toRight">
	<div>Medicina Interna A - Piano 6, Sala 2</div>
	<div>{{ user_role_str }}: {{ user_name }}</div>
</div>

templates/jquery-pages/doc1.html
{% extends "jquery-pages/base-page.html" %}

{% block header %}
{% include "jquery-pages/header_and_navbar.html" %}
{% endblock header %}

{% block content %}
	<div data-role="content">
		{% include "jquery-pages/div-info.html" %}
		
		<!-- Patient data -->
		<h1>Dati Paziente</h1>
		<table class="clickabletable">
			<thead>
				<th>Apparati</th>
				<th>Referto</th>
				<th>Si (1)</th>
				<th>No (0)</th>
				<th>Non so (0.5)</th>
				<th>Totale</th>
			</thead>
			<tbody>
				<tr>
					<td rowspan="3"><h1>A</h1></td>
					<td class="table-hdr">Addensamento polmone</td>
					<td data-payoff="1" class="clickableCell highlighted"></td>
					<td data-payoff="0" class="clickableCell"></td>
					<td data-payoff="0.5" class="clickableCell"></td>
					<td class="rowTotal">1</td>	
				</tr>
				<tr>
					<td class="table-hdr">Versamento pleurico</td>
					<td data-payoff="1" class="clickableCell highlighted"></td>
					<td data-payoff="0" class="clickableCell"></td>
					<td data-payoff="0.5" class="clickableCell"></td>
					<td class="rowTotal">1</td>
				</tr>
				<tr>
					<td class="table-hdr">Edema polmonare</td>
					<td data-payoff="1" class="clickableCell"></td>
					<td data-payoff="0" class="clickableCell"></td>
					<td data-payoff="0.5" class="clickableCell highlighted"></td>
					<td class="rowTotal">0.5</td>
				</tr>
				
				<tr>
					<td rowspan="4"><h1>B</h1></td>
					<td class="table-hdr">Versamento addominale</td>
					<td data-payoff="1" class="clickableCell"></td>
					<td data-payoff="0" class="clickableCell"></td>
					<td data-payoff="0.5" class="clickableCell highlighted"></td>
					<td class="rowTotal">0.5</td>
				</tr>
				<tr>
					<td class="table-hdr">Colecistite</td>
					<td data-payoff="1" class="clickableCell"></td>
					<td data-payoff="0" class="clickableCell"></td>
					<td data-payoff="0.5" class="clickableCell highlighted"></td>
					<td class="rowTotal">0.5</td>
				</tr>
				<tr>
					<td class="table-hdr">Occlusione instestinale</td>
					<td data-payoff="1" class="clickableCell"></td>
					<td data-payoff="0" class="clickableCell highlighted"></td>
					<td data-payoff="0.5" class="clickableCell"></td>
					<td class="rowTotal">0</td>
				</tr>
				<tr>
					<td class="table-hdr">Idronefrosi</td>
					<td data-payoff="1" class="clickableCell"></td>
					<td data-payoff="0" class="clickableCell highlighted"></td>
					<td data-payoff="0.5" class="clickableCell"></td>
					<td class="rowTotal">0</td>
				</tr>
				
				<tr>
					<td rowspan="2"><h1>C</h1></td>
					<td class="table-hdr">TVP ileo-femorale</td>
					<td data-payoff="1" class="clickableCell"></td>
					<td data-payoff="0" class="clickableCell highlighted"></td>
					<td data-payoff="0.5" class="clickableCell"></td>
					<td class="rowTotal">0</td>				
				</tr>
				<tr>
					<td class="table-hdr">TVP poplitea</td>
					<td data-payoff="1" class="clickableCell"></td>
					<td data-payoff="0" class="clickableCell highlighted"></td>
					<td data-payoff="0.5" class="clickableCell"></td>
					<td class="rowTotal">0</td>
				</tr>
				
				<tr>
					<td colspan="5">BBs-Us score:</td>
					<td id="bbs-us-score" class="total">3.5</td>
				</tr>
			</tbody>	
		</table>

	</div>
{% endblock content %}

templates/jquery-pages/doc2.html
{% extends "jquery-pages/base-page.html" %}

{% block header %}
{% include "jquery-pages/header_and_navbar.html" %}
{% endblock header %}

{% block content %}
	<div data-role="content">
		{% include "jquery-pages/div-info.html" %}
		
		<!-- Patient data -->
		<h1>Esoscopia</h1>
		<table class="clickabletable">
			<thead>
				<th>Apparati</th>
				<th>Commento</th>
			</thead>
			<tbody>
				<tr>
					<td>A</td>
					<td><input type="text" placeholder="Commento Edema polm..." /></td>
				</tr>
				<tr>
					<td>B</td>
					<td><input type="text" placeholder="Commento Occlusione int..." /></td>
				</tr>
				<tr>
					<td>C</td>
					<td><input type="text" placeholder="Commento TVP fem-popl..." /></td>
				</tr>
			</tbody>	
		</table>

	</div>
{% endblock content %}

templates/jquery-pages/doc3.html
{% extends "jquery-pages/base-page.html" %}

{% block header %}
{% include "jquery-pages/header_and_navbar.html" %}
{% endblock header %}

{% block content %}
	<div data-role="content">
		{% include "jquery-pages/div-info.html" %}
		
		<!-- Patient data -->
		<h1>Esito</h1>
		<table class="clickabletable">
			<thead>
				<th>Valori</th>
				<th>Totale</th>
			</thead>
			<tbody>
				<tr>
					<td>MEWS</td>
					<td>3</td>
				</tr>
				<tr>
					<td>IP</td>
					<td>18</td>
				</tr>
				<tr>
					<td>BBs-Us</td>
					<td>4</td>
				</tr>
				<tr>
					<td>Total Score</td>
					<td>25</td>
				</tr>
				<tr>
					<td>Destinazione Area</td>
					<td class="destination"><h1>R</h1></td>
				</tr>
			</tbody>	
		</table>

	</div>
{% endblock content %}

templates/jquery-pages/doc4.html
{% extends "jquery-pages/base-page.html" %}

{% block header %}
{% include "jquery-pages/header_and_navbar.html" %}
{% endblock header %}

{% block content %}
	<div data-role="content">
		{% include "jquery-pages/div-info.html" %}
		
		<!-- Patient data -->
		<h1>Conclusioni</h1>
		<table class="clickabletable">
			<thead>
				<th>Accordo BBUS/Clinica</th>
				<th>Motivo</th>
			</thead>
			<tbody>
				<tr>
					<td>SI</td>
					<td>-</td>
				</tr>
				<tr>
					<td>NO</td>
					<td>Angina Instabile</td>
				</tr>
			</tbody>	
		</table>

	</div>
{% endblock content %}

templates/jquery-pages/header_and_navbar.html
<div data-role="header" data-position="inline" data-theme="b">
	<h1>Bedside</h1>
	<a data-direction="reverse" data-icon="home" data-ajax="false" href="/">Logout</a>
	<div data-role="navbar" data-iconpos="right">
		<ul>
			<li><a href="{{ prev_href }}" data-direction="reverse" data-icon="back">{{ prev_str }}</a></li>
			<li><a href="{{ next_href }}" data-icon="forward">{{ next_str }}</a></li>
		</ul>
	</div>
</div>

templates/jquery-pages/login.html
{% extends "jquery-pages/base-page.html" %}

{% block header %}
	<div data-role="header" data-theme="b">
		<h1>Bedside</h1>
		<a data-direction="reverse" data-icon="back" href="#role-selection">Back</a>
	</div>
{% endblock header %}

{% block content %}
	<div data-role="content">
		{% if form.errors %}
			<p>Your username and password didn't match. Please try again.</p>
		{% endif %}
			
		<h3>Login {{ user_role }}</h3>
		<form action="{{ action }}" method="post" id="login-form" data-ajax="false">
			{% csrf_token %}
			<ul data-role="listview" data-inset="true" data-theme="c">
				<li data-role="fieldcontain">
				<div data-role="fieldcontain">
					<label for="username" class="ui-hidden-accessible">Nome utente:</label>
					<input type="text" name="username" id="username" value="" placeholder="Nome utente..."/>
				</div>
				<div data-role="fieldcontain">
					<label for="password" class="ui-hidden-accessible">Password:</label>
					<input type="password" name="password" id="password" value="" placeholder="Password..."/>
				</div>
				</li>
				<li data-role="fieldcontain">
					<button type="submit" data-theme="b">Login</button>
				</li>
			</ul>
		</form>
	</div>
{% endblock content %}

{% block footer %}
{% endblock %}

templates/jquery-pages/patient-review.html
{% extends "jquery-pages/base-page.html" %}

{% block header %}
{% include "jquery-pages/header_and_navbar.html" %}
{% endblock header %}

{% block content %}
	<div data-role="content">
		{% include "jquery-pages/div-info.html" %}
		
		<!-- Patient data -->
		<h1>Dati Paziente</h1>
		<table>
			<thead>
				<th>ID</th>
				<th>Nome</th>
				<th>Cognome</th>
				<th>Sesso</th>
				<th>Età</th>
				<th>Data Ricovero</th>
				<th>Reparto Inviante</th>
			</thead>
			<tbody>
				<tr>
					<td>00016438</td>
					<td>Mario</td>
					<td>Rossi</td>
					<td>M</td>
					<td>42</td>
					<td>15-01-2012 10:15</td>
					<td>PS</td>
				</tr>
			</tbody>
		</table>

		<!-- Diagnosis -->
		<h3>Diagnosi</h3>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam arcu lorem, consectetur placerat aliquam sit amet, tincidunt viverra lorem. In nulla eros, ullamcorper nec tempus id, fermentum semper lorem. Proin felis orci, tincidunt non pharetra eu, lacinia nec justo. Praesent tellus metus, pharetra id posuere varius, rutrum sed nulla. Nulla a gravida eros. Pellentesque rhoncus velit sed quam pellentesque porta. Duis euismod rhoncus ornare. Integer quis felis mi.<br/><br/>
			Sed odio felis, molestie sit amet tincidunt a, cursus sed sem. Pellentesque et enim ut dui lacinia rutrum. Aenean sed cursus sem. Nullam pulvinar porttitor iaculis. Integer quis arcu nulla, id bibendum nulla. Integer euismod sagittis ante, vitae malesuada nibh egestas sit amet. Donec vel sem a nisl faucibus tincidunt. Duis at ante sed lorem egestas congue. Quisque dictum nulla ut neque tincidunt blandit. Nam auctor elit at libero dignissim vehicula ac a mauris. Nullam lectus nisl, luctus a tristique sit amet, vestibulum et orci. Aliquam augue nibh, sodales id vehicula vel, gravida mattis mi. Vivamus volutpat vehicula interdum. Vivamus eget odio felis. Etiam dictum risus non tortor ultricies sit amet sollicitudin odio accumsan. Cras sit amet enim nisl.
		</p>
	</div>
{% endblock content %}

templates/quest_list.html
{% extends "mobi.html" %}

{% block content %}
    <div class="content-primary">
    
    <h3 id="welcome-string">Benvenuto {{ user.first_name|escape }}!</h3>
	
	{% if todo.count > 0 %}
	<ul data-role="listview" data-inset="true">
		<li data-role="list-divider">Questionari da compilare <span class="ui-li-count">{{ todo.count }}</span></li>
		{% for q in todo %}
			<li><a href="/givings/compile/{{ q.gid }}/" data-ajax="false">
				{% for t in q.quid.questionnaire_lang_set.all %}
				{% if t.lang == request.session.django_language %}
					<h3>{{ t.title }}</h3>
				{% endif %}
				{% endfor %}
				
				<p class="ui-li-aside"><strong>{{ q.did }}</strong></p>
				<p>{{ q.extra_info }}</p>
				<p>Compilare entro le ore <strong>{{ q.to_date.time }}</strong> del giorno <strong>{{ q.to_date.date }}</strong></p>
			</a></li>
		{% endfor %}
	</ul>
	{% else %}
	Al momento non vi sono questionari da compilare.
	{% endif %}
	</div>
	
	<div class="content-secondary">
	<div data-role="collapsible" data-collapsed="true" data-theme="b" data-content-theme="d">
	Side content
	</div>
	
	</div>
	
	<!--a href="#login" data-rel="dialog" data-role="button">Login</a-->
{% endblock %}